export default {
  "code": 200,
  "msg": "OK",
  "data": {
    "content": [{
      "realtimeId": "386198",
      "realtimeTitle": "港股异动 | 富智康集团(02038)盘中涨超8% 传闻称富士康开始测试折叠版iPhone设计",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386198.html",
      "stockCodes": ["02038"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "富智康集团",
        "stockTcSimpleName": "富智康集團",
        "stockEnSimpleName": "FIH",
        "stockCnFullName": "富智康集团有限公司",
        "stockTcFullName": "富智康集團有限公司",
        "stockEnFullName": "FIH Mobile Ltd.",
        "instrCode": "02038",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 14:24:04",
      "exclusiveLabels": ["智通财经", "富智康集团"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230142309_27879.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386197",
      "realtimeTitle": "油价年内暴跌再掀原油基准论战！上海原油期货地位有望抬升？",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386197.html",
      "stockCodes": ["00857", "00883", "00386"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "中国石油股份",
        "stockTcSimpleName": "中國石油股份",
        "stockEnSimpleName": "PETROCHINA",
        "stockCnFullName": "中国石油天然气股份有限公司 - H股",
        "stockTcFullName": "中國石油天然氣股份有限公司 - H股",
        "stockEnFullName": "PetroChina Co. Ltd. - H Shares",
        "instrCode": "00857",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "中国海洋石油",
        "stockTcSimpleName": "中國海洋石油",
        "stockEnSimpleName": "CNOOC",
        "stockCnFullName": "中国海洋石油有限公司",
        "stockTcFullName": "中國海洋石油有限公司",
        "stockEnFullName": "CNOOC Ltd.",
        "instrCode": "00883",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "中国石油化工股份",
        "stockTcSimpleName": "中國石油化工股份",
        "stockEnSimpleName": "SINOPEC CORP",
        "stockCnFullName": "中国石油化工股份有限公司 - H股",
        "stockTcFullName": "中國石油化工股份有限公司 - H股",
        "stockEnFullName": "China Petroleum & Chemical Corporation - H Shares",
        "instrCode": "00386",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 14:18:48",
      "exclusiveLabels": ["原油", "石油", "油价"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230141159_22640.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386193",
      "realtimeTitle": "超40%下跌空间？Cowen仅上调特斯拉(TSLA.US)目标价至380美元",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386193.html",
      "stockCodes": ["TSLA.US"],
      "stockList": [{
        "exchangeType": "NASDAQ",
        "exchangeName": "纳斯达克股票交易所",
        "stockCnSimpleName": "特斯拉",
        "stockTcSimpleName": "特斯拉",
        "stockEnSimpleName": "Tesla, Inc. Common Stock",
        "stockCnFullName": "特斯拉",
        "stockTcFullName": "特斯拉",
        "stockEnFullName": "Tesla, Inc. Common Stock",
        "instrCode": "TSLA",
        "marketType": "US_STOCK",
        "marketName": "美股"
      }],
      "sendTime": "2020-12-30 14:06:00",
      "exclusiveLabels": ["特斯拉", "汽车"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230135724_78858.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386194",
      "realtimeTitle": "港股异动 | 中芯国际(00981)午后升逾10% 传将针对EUV光刻设备寻求与阿斯麦进行谈判",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386194.html",
      "stockCodes": ["00981"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "中芯国际",
        "stockTcSimpleName": "中芯國際",
        "stockEnSimpleName": "SMIC",
        "stockCnFullName": "中芯国际集成电路制造有限公司",
        "stockTcFullName": "中芯國際集成電路製造有限公司",
        "stockEnFullName": "Semiconductor Manufacturing International Corporation",
        "instrCode": "00981",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 14:03:47",
      "exclusiveLabels": ["智通财经", "中芯国际"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230140230_67526.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386192",
      "realtimeTitle": "国泰君安：独立代理人制度破冰，对专属代理人影响有限——关于发展独立个人保险代理人的通知点评",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386192.html",
      "stockCodes": ["02318", "01336", "02601"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "中国平安",
        "stockTcSimpleName": "中國平安",
        "stockEnSimpleName": "PING AN",
        "stockCnFullName": "中国平安保险(集团)股份有限公司 - H股",
        "stockTcFullName": "中國平安保險(集團)股份有限公司 - H股",
        "stockEnFullName": "Ping An Insurance (Group) Co. of Chin",
        "instrCode": "02318",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "新华保险",
        "stockTcSimpleName": "新華保險",
        "stockEnSimpleName": "NCI",
        "stockCnFullName": "新华人寿保险股份有限公司 - H股",
        "stockTcFullName": "新華人壽保險股份有限公司 - H股",
        "stockEnFullName": "New China Life Insurance Co. Ltd. - H Shares",
        "instrCode": "01336",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "中国太保",
        "stockTcSimpleName": "中國太保",
        "stockEnSimpleName": "CPIC",
        "stockCnFullName": "中国太平洋保险(集团)股份有限公司 - H股",
        "stockTcFullName": "中國太平洋保險(集團)股份有限公司 - H股",
        "stockEnFullName": "China Pacific Insurance (Group) Co",
        "instrCode": "02601",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 13:51:27",
      "exclusiveLabels": ["独立个人保险代理人", "保险"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230134734_68680.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386190",
      "realtimeTitle": "App、中资券商夹击之下，香港传统券商边缘化，今年36家结业",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386190.html",
      "stockCodes": ["01428"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "耀才证券金融",
        "stockTcSimpleName": "耀才證券金融",
        "stockEnSimpleName": "BRIGHT SMART",
        "stockCnFullName": "耀才证券金融集团有限公司",
        "stockTcFullName": "耀才證券金融集團有限公司",
        "stockEnFullName": "Bright Smart Securities & Commodities Group Ltd.",
        "instrCode": "01428",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 13:50:40",
      "exclusiveLabels": ["香港传统券商", "内地券商"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230134344_88714.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386189",
      "realtimeTitle": "港股异动︱威高股份(01066)涨超6% 拟向控股股东收购Wego Healthcare Fund Holding Corporation全部股权",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386189.html",
      "stockCodes": ["01066"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "威高股份",
        "stockTcSimpleName": "威高股份",
        "stockEnSimpleName": "WEIGAO GROUP",
        "stockCnFullName": "山东威高集团医用高分子制品股份有限公司 - H股",
        "stockTcFullName": "山東威高集團醫用高分子製品股份有限公司 - H股",
        "stockEnFullName": "Shandong Weigao Group Medical Polymer Co. Ltd. - H Shares",
        "instrCode": "01066",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 13:43:19",
      "exclusiveLabels": ["威高股份", "收购"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230134157_85099.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386185",
      "realtimeTitle": "百济神州(06160)TIGIT单克隆抗体获批三种癌症临床适应症",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386185.html",
      "stockCodes": ["06160"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "百济神州",
        "stockTcSimpleName": "百濟神州",
        "stockEnSimpleName": "BEIGENE",
        "stockCnFullName": "百济神州有限公司",
        "stockTcFullName": "百濟神州有限公司",
        "stockEnFullName": "BeiGen",
        "instrCode": "06160",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 13:03:22",
      "exclusiveLabels": ["百济神州", "港股"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230125928_49010.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386171",
      "realtimeTitle": "新股研报丨裕程物流(08489)拟港股创业板上市，不确定因素颇多，预期股价波幅相对较大",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386171.html",
      "stockCodes": ["08489"],
      "stockList": [],
      "sendTime": "2020-12-30 11:52:30",
      "exclusiveLabels": ["裕程物流", "货运"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230113309_15045.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386174",
      "realtimeTitle": "港股异动 | 普拉达(01913)涨超7%创逾六年新高 拟4000万欧元出售Via Spiga物业",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386174.html",
      "stockCodes": ["01913"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "普拉达",
        "stockTcSimpleName": "普拉達",
        "stockEnSimpleName": "PRADA",
        "stockCnFullName": "PRADA S.p.A.",
        "stockTcFullName": "PRADA S.p.A.",
        "stockEnFullName": "PRADA S.p.A.",
        "instrCode": "01913",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 11:51:07",
      "exclusiveLabels": ["智通财经", "普拉达"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230114932_23501.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386170",
      "realtimeTitle": "港股异动 | 信达生物(01801)涨近8%再破顶 月内累涨近60% 5天内斩获3个适应症",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386170.html",
      "stockCodes": ["01801"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "信达生物",
        "stockTcSimpleName": "信達生物",
        "stockEnSimpleName": "INNOVENT BIO",
        "stockCnFullName": "信达生物制药",
        "stockTcFullName": "信達生物製藥",
        "stockEnFullName": "Innovent Biologic",
        "instrCode": "01801",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 11:36:55",
      "exclusiveLabels": ["智通财经", "信达生物"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230113424_62782.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386165",
      "realtimeTitle": "华创非银：基本面向好未改，保险配置正当时",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386165.html",
      "stockCodes": ["02318", "02628", "01336", "02601"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "中国平安",
        "stockTcSimpleName": "中國平安",
        "stockEnSimpleName": "PING AN",
        "stockCnFullName": "中国平安保险(集团)股份有限公司 - H股",
        "stockTcFullName": "中國平安保險(集團)股份有限公司 - H股",
        "stockEnFullName": "Ping An Insurance (Group) Co. of Chin",
        "instrCode": "02318",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "中国人寿",
        "stockTcSimpleName": "中國人壽",
        "stockEnSimpleName": "CHINA LIFE",
        "stockCnFullName": "中国人寿保险股份有限公司 - H股",
        "stockTcFullName": "中國人壽保險股份有限公司 - H股",
        "stockEnFullName": "China Life Insurance Co. Ltd. - H Shares",
        "instrCode": "02628",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "新华保险",
        "stockTcSimpleName": "新華保險",
        "stockEnSimpleName": "NCI",
        "stockCnFullName": "新华人寿保险股份有限公司 - H股",
        "stockTcFullName": "新華人壽保險股份有限公司 - H股",
        "stockEnFullName": "New China Life Insurance Co. Ltd. - H Shares",
        "instrCode": "01336",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "中国太保",
        "stockTcSimpleName": "中國太保",
        "stockEnSimpleName": "CPIC",
        "stockCnFullName": "中国太平洋保险(集团)股份有限公司 - H股",
        "stockTcFullName": "中國太平洋保險(集團)股份有限公司 - H股",
        "stockEnFullName": "China Pacific Insurance (Group) Co",
        "instrCode": "02601",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 11:24:20",
      "exclusiveLabels": ["保险", "行业策略报告"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230105612_58616.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386167",
      "realtimeTitle": "新股研报丨Legion Consortium(02129)为新加坡物流服务供应商，市值偏小，股价或较波动",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386167.html",
      "stockCodes": ["02129"],
      "stockList": [],
      "sendTime": "2020-12-30 11:20:19",
      "exclusiveLabels": ["Legion Consortium", "新加坡"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230111454_56218.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386163",
      "realtimeTitle": "解码“金融巨鳄”索罗斯的投资哲学",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386163.html",
      "stockCodes": [" "],
      "stockList": [],
      "sendTime": "2020-12-30 11:17:19",
      "exclusiveLabels": ["金融巨鳄", "索罗斯"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230110713_57933.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386164",
      "realtimeTitle": "港股异动 | 体育用品股普涨 特步(01368)涨逾8% 李宁(02331)、安踏(02020)齐创新高",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386164.html",
      "stockCodes": ["01368", "01361", "02331", "02020"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "特步国际",
        "stockTcSimpleName": "特步國際",
        "stockEnSimpleName": "XTEP INT'L",
        "stockCnFullName": "特步国际控股有限公司",
        "stockTcFullName": "特步國際控股有限公司",
        "stockEnFullName": "Xtep International Holdings Ltd.",
        "instrCode": "01368",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "３６１度",
        "stockTcSimpleName": "３６１度",
        "stockEnSimpleName": "361 DEGREES",
        "stockCnFullName": "361度国际有限公司",
        "stockTcFullName": "361度國際有限公司",
        "stockEnFullName": "361 Degrees International Ltd.",
        "instrCode": "01361",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "李宁",
        "stockTcSimpleName": "李寧",
        "stockEnSimpleName": "LI NING",
        "stockCnFullName": "李宁有限公司",
        "stockTcFullName": "李寧有限公司",
        "stockEnFullName": "Li Ning Co. Ltd.",
        "instrCode": "02331",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "安踏体育",
        "stockTcSimpleName": "安踏體育",
        "stockEnSimpleName": "ANTA SPORTS",
        "stockCnFullName": "安踏体育用品有限公司",
        "stockTcFullName": "安踏體育用品有限公司",
        "stockEnFullName": "ANTA Sports Products Ltd.",
        "instrCode": "02020",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 11:10:19",
      "exclusiveLabels": ["智通财经", "体育用品股"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230110913_41861.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386155",
      "realtimeTitle": "港股异动 | SaaS概念普涨 兑吧(01753)涨超7% 招银研究称国内SAAS发展将迎来黄金十年",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386155.html",
      "stockCodes": ["01753", "03888", "00268", "06988"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "兑吧",
        "stockTcSimpleName": "兌吧",
        "stockEnSimpleName": "DUIBA",
        "stockCnFullName": "兑吧集团有限公司",
        "stockTcFullName": "兌吧集團有限公司",
        "stockEnFullName": "Duiba Group Ltd.",
        "instrCode": "01753",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "金山软件",
        "stockTcSimpleName": "金山軟件",
        "stockEnSimpleName": "KINGSOFT",
        "stockCnFullName": "金山软件有限公司",
        "stockTcFullName": "金山軟件有限公司",
        "stockEnFullName": "Kingsoft Corporation Ltd.",
        "instrCode": "03888",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "金蝶国际",
        "stockTcSimpleName": "金蝶國際",
        "stockEnSimpleName": "KINGDEE INT'L",
        "stockCnFullName": "金蝶国际软件集团有限公司",
        "stockTcFullName": "金蝶國際軟件集團有限公司",
        "stockEnFullName": "Kingdee International Software Group Co. Ltd.",
        "instrCode": "00268",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      },
      {
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "乐享互动",
        "stockTcSimpleName": "樂享互動",
        "stockEnSimpleName": "JOY SPREADER",
        "stockCnFullName": "乐享互动有限公司",
        "stockTcFullName": "樂享互動有限公司",
        "stockEnFullName": "Joy Spreader Interactive Technology. Ltd",
        "instrCode": "06988",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 11:01:56",
      "exclusiveLabels": ["智通财经", "SaaS概念"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230104812_58411.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386159",
      "realtimeTitle": "港股异动 | 农夫山泉(09633)涨超7%破顶 花旗称市场地位确保长期增长潜力 上调目标价37%",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386159.html",
      "stockCodes": ["09633"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "农夫山泉",
        "stockTcSimpleName": "農夫山泉",
        "stockEnSimpleName": "NONGFU SPRING",
        "stockCnFullName": "农夫山泉股份有限公司 - H股",
        "stockTcFullName": "農夫山泉股份有限公司 - H股",
        "stockEnFullName": "Nongfu Spring Co",
        "instrCode": "09633",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 10:58:38",
      "exclusiveLabels": ["智通财经", "农夫山泉"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230105704_37630.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386151",
      "realtimeTitle": "新股研报丨达丰设备(02153)是中国首家外资塔式起重机服务供应商，两名基石占发售股份32.5%",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386151.html",
      "stockCodes": ["02153"],
      "stockList": [],
      "sendTime": "2020-12-30 10:33:51",
      "exclusiveLabels": ["达丰设备", "新股"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230102414_11061.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386146",
      "realtimeTitle": "大摩：首予一起教育科技(YQ.US)“增持”评级 预计2021年营收将增长134%",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386146.html",
      "stockCodes": ["YQ.US"],
      "stockList": [{
        "exchangeType": "NASDAQ",
        "exchangeName": "纳斯达克股票交易所",
        "stockCnSimpleName": "M17 Entertainment Ltd ADR",
        "stockTcSimpleName": "M17 Entertainment Ltd ADR",
        "stockEnSimpleName": "M17 Entertainment Limited American Depositary Shares, each representing 8 Class A Ordinary Shares",
        "stockCnFullName": "M17 Entertainment Ltd ADR",
        "stockTcFullName": "M17 Entertainment Ltd ADR",
        "stockEnFullName": "M17 Entertainment Limited American Depositary Shares, each representing 8 Class A Ordinary Shares",
        "instrCode": "YQ",
        "marketType": "US_STOCK",
        "marketName": "美股"
      }],
      "sendTime": "2020-12-30 10:23:05",
      "exclusiveLabels": ["一起教育科技", "评级"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230101754_97635.png?x-oss-process=image/format,jpg/quality,Q_80"
    },
    {
      "realtimeId": "386147",
      "realtimeTitle": "港股异动 | 东岳集团(00189)续涨超10% 疫苗冷链需求拉动制冷剂价格持续走强",
      "realtimeUri": "http://www.zhitongcaijing.com/content/detail/386147.html",
      "stockCodes": ["00189"],
      "stockList": [{
        "exchangeType": "SEHK",
        "exchangeName": "香港证券交易所",
        "stockCnSimpleName": "东岳集团",
        "stockTcSimpleName": "東岳集團",
        "stockEnSimpleName": "DONGYUE GROUP",
        "stockCnFullName": "东岳集团有限公司",
        "stockTcFullName": "東岳集團有限公司",
        "stockEnFullName": "Dongyue Group Ltd.",
        "instrCode": "00189",
        "marketType": "HK_STOCK",
        "marketName": "港股"
      }],
      "sendTime": "2020-12-30 10:22:03",
      "exclusiveLabels": ["智通财经", "东岳集团"],
      "realtimeAuthor": "智通财经网",
      "realtimeSource": "THIRDPARTY_REALTIME",
      "realtimeDetail": null,
      "stockRating": null,
      "readingVolume": 0,
      "exclusiveVip": null,
      "coverUri": "https://img.zhitongcaijing.com/image/20201230/20201230102055_24184.png?x-oss-process=image/format,jpg/quality,Q_80"
    }],
    "totalPages": 303,
    "totalElements": 6057,
    "page": 0,
    "size": 20,
    "offset": 0
  }
}